name: Deploy
on: push
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Initialize
      run: |
        mkdir BuildResults
        mkdir BuildResults/SimpleApps-Release
    - name: build library
      run: |
        dotnet restore
        dotnet msbuild -nologo -restore -p:Configuration=Release TrivialMvvm
        cp TrivialMvvm/bin/Release/*.nupkg BuildResults/SimpleApps-Release
    - name: build standard suite (Release)
      run: |
        dotnet msbuild -nologo -p:Configuration=Release TestCore
    - name: run standard suite (Release)
      run: |
        dotnet test -c Release TestCore
    - uses: actions/upload-artifact@v1
      with:
        name: RunnerOutput-Release
        path: BuildResults/SimpleApps-Release
