name: Test

on: [push]

jobs:
  Test1:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Do test job
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        dotnet restore
        msbuild -t:WcMvvm461 -p:Configuration=Debug -p:Platform="Any CPU"
        msbuild -t:Test472 -p:Configuration=Debug -p:Platform="Any CPU"
        vstest.console.exe Test472\bin\Debug\Test472.dll /EnableCodeCoverage
        set > vars.txt
    - name: Do save results job
        uses: actions/upload-artifact@v1
        with:
          name: Vars report
          path: vars.txt
