name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: |
        mkdir BuildResults
        mkdir BuildResults\SimpleApps-Debug
    - name: Build library
      run: |
        dotnet restore
        dotnet build -c Debug TrivialMvvm
        copy TrivialMvvm\bin\Release\*.nupkg BuildResults\SimpleApps-Debug
    - name: Build standard suite
      run: |
        dotnet restore TestCore
        dotnet build -c Debug TestCore
    - name: Run standard suite
      run: dotnet test TestCore
    - uses: actions/upload-artifact@v1
      with:
        name: RunnerOutput-Debug
        path: BuildResults\SimpleApps-Debug
