name: work1

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build, test
      run: |
        echo building Debug
        set PATH=%PATH%;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
        echo %PATH%
        msbuild -t:WcMvvm461 -p:Configuration=Debug -p:Platform="Any CPU"
        dotnet restore
        msbuild -t:Test472 -p:Configuration=Debug -p:Platform="Any CPU"
        echo testing Debug
        dotnet vstest Test472\bin\Debug\Test472.dll
        echo building Release
        msbuild -t:WcWpfMvvm -p:Configuration=Debug -p:Platform="Any CPU"
        msbuild -t:WcMvvm461 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:Test472 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:WcWpfMvvm -p:Configuration=Release -p:Platform="Any CPU"
        echo test Release
        dotnet vstest Test472\bin\Release\Test472.dll
        echo reporting
        dotnet --version
