name: work1

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
    - name: Build, test
      run: |
        echo building Debug
        msbuild -t:WcMvvm461 -p:Configuration=Debug -p:Platform="Any CPU"
        msbuild -t:Test472 -p:Configuration=Debug -p:Platform="Any CPU"
        echo testing Debug
        vstest.console Test472\bin\Debug\Test472.dll
        echo building Release
        msbuild -t:WcWpfMvvm -p:Configuration=Debug -p:Platform="Any CPU"
        msbuild -t:WcMvvm461 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:Test472 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:WcWpfMvvm -p:Configuration=Release -p:Platform="Any CPU"
        echo test Release
        dotnet vstest Test472\bin\Release\Test472.dll
        echo deploying
        dotnet --version
        where vstest.console.exe
        echo PATH=%PATH%
